language: node_js

sudo: required

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm test

after_success:
  - docker build -t fibo-client ./client
  - docker build -t fibo-nginx ./nginx
  - docker build -t fibo-server ./server
  - docker build -t fibo-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push girirbabu/fibo:fibo-client
  - docker push girirbabu/fibo:fibo-nginx
  - docker push girirbabu/fibo:fibo-server
  - docker push girirbabu/fibo:fibo-worker

