language: node_js

sudo: required

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm test

after_success:
  - docker build -t girirbabu/fibo-client ./client
  - docker build -t girirbabu/fibo-nginx ./nginx
  - docker build -t girirbabu/fibo-server ./server
  - docker build -t girirbabu/fibo-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push girirbabu/fibo-client
  - docker push girirbabu/fibo-nginx
  - docker push girirbabu/fibo-server
  - docker push girirbabu/fibo-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: fibo-docker
  env: FiboDocker-env
  bucket_name: elasticbeanstalk-us-east-2-727869003203
  bucket_path: fibo-bucket
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

